require("danmharris.opt")
require("danmharris.plugin")
require("danmharris.plugin.catppuccin")
require("danmharris.plugin.treesitter")
require("danmharris.plugin.nvim-tree")
require("danmharris.plugin.which-key")
require("danmharris.plugin.mason")
require("danmharris.plugin.lspconfig")
