import = ["/home/dan/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono NF"

[window]
decorations = "full"
